### ISSUE TITLE
This content is stolen

### ISSUE THREAD

**Issue by florianwalther-private** [bktowett/AndelaDIWorkshop#1]
The whole project's code is copied from my Dagger tutorial
https://www.youtube.com/playlist?list=PLrnPJCHvNZuA2ioi4soDZKz8euUQnJW65

**Comment by bktowett** [comment]
<img width="1042" alt="Screenshot 2020-01-02 at 20 56 14" src="https://user-images.githubusercontent.com/18550843/71683022-6aeb9f80-2da2-11ea-8204-902bd20f6baf.png">

**Comment by JoelSalzesson** [comment]
It's still stolen.
